apiVersion: v1
kind: Service
metadata:
  name: inference-service
  namespace: threat-detection
  labels:
    app: inference-service
spec:
  type: ClusterIP
  selector:
    app: inference-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
