apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: threat-detection
  labels:
    app: api-service
spec:
  type: LoadBalancer
  selector:
    app: api-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
